### ISSUE TITLE
My Facebook group was hacked

### ISSUE THREAD

**Issue by Abuahmed2020** [hackathons-com/Rails-MongoDB-Devise-test#9]
i need help please , my Facebook group was hacked

**Comment by rodrigoargumedo** [comment]
Closing issue.

Check the Facebook Groups [Help Center](https://www.facebook.com/help/1075368719167893/?helpref=hc_fnav) to report a problem. If an individual account was hacked, please go to this link [here](https://facebook.com/hacked).
